FROM php:5.6-apache

LABEL traefik.http.routers.static.rule=Host(`res.ch`)
LABEL traefik.http.services.static.loadbalancer.server.port=80

RUN apt-get update && apt-get install -y nano

COPY content/ /var/www/html/

